DATASET: 'cifar100'
MODEL:
  ARCH: "vit_tiny_patch16_224"
  NUM_CLASSES: 100
  DROPIT: True
  PRETRAINED: True
DROPIT:
  STRATEGY: "parallel_mink"
  GAMMA: 0.9
DATALOADER:
  NUM_WORKERS: 8
SOLVER:
  LR: 0.03
  BATCH_SIZE: 512
  MAX_EPOCHS: 20
  WARMUP_EPOCHS: 5
NUM_GPUS: 2
CHECK_VAL_EVERY_N_EPOCH: 1